# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: '0xa468A8013A16351D16951e04736ebcab663B5F6c'
    chainName: holesky
    collateralAddressOrDenom: '0x94373a4919B3240D86eA41593D5eBa789FEF3848'
    connections:
      - token: ethereum|tangletestnet|0x407AE90DBa08C816B62033221b422e95AA248f63
    decimals: 18
    name: Wrapped Ether
    standard: EvmHypCollateral
    symbol: WETH
  - addressOrDenom: '0x407AE90DBa08C816B62033221b422e95AA248f63'
    chainName: tangletestnet
    connections:
      - token: ethereum|holesky|0xa468A8013A16351D16951e04736ebcab663B5F6c
    decimals: 18
    name: Wrapped Ether
    standard: EvmHypSynthetic
    symbol: WETH
