# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: '0xdFe0fbA0F8C62278DF4A9fDc787F9cFF28522FD3'
    chainName: holesky
    collateralAddressOrDenom: '0x94373a4919B3240D86eA41593D5eBa789FEF3848'
    connections:
      - token: ethereum|tangletestnet|0x200DE548e393c38ee80482e9c5c186CBA7096ad4
    decimals: 18
    name: Wrapped Ether
    standard: EvmHypCollateral
    symbol: WETH
  - addressOrDenom: '0x200DE548e393c38ee80482e9c5c186CBA7096ad4'
    chainName: tangletestnet
    connections:
      - token: ethereum|holesky|0xdFe0fbA0F8C62278DF4A9fDc787F9cFF28522FD3
    decimals: 18
    name: Wrapped Ether
    standard: EvmHypSynthetic
    symbol: WETH
