name: Check Clean

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches: ['main', 'feat/**', 'feature/**']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          
      - name: Enable Corepack
        run: corepack enable

      - name: format
        run: |
          yarn install
          yarn format:check

      - name: lint
        run: |
          yarn install
          yarn lint:check

      - name: ts-check
        run: |
          yarn install
          yarn ts-check
